// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: password-service.proto

package ronan_hanley.dist_sys.user_account_service.proto;

/**
 * Protobuf type {@code HashResponse}
 */
public  final class HashResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:HashResponse)
    HashResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use HashResponse.newBuilder() to construct.
  private HashResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private HashResponse() {
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new HashResponse();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private HashResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            userId_ = input.readInt32();
            break;
          }
          case 18: {
            HashPair.Builder subBuilder = null;
            if (hashPair_ != null) {
              subBuilder = hashPair_.toBuilder();
            }
            hashPair_ = input.readMessage(HashPair.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(hashPair_);
              hashPair_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return PasswordServiceProto.internal_static_HashResponse_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return PasswordServiceProto.internal_static_HashResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            HashResponse.class, HashResponse.Builder.class);
  }

  public static final int USERID_FIELD_NUMBER = 1;
  private int userId_;
  /**
   * <code>int32 userId = 1;</code>
   */
  public int getUserId() {
    return userId_;
  }

  public static final int HASHPAIR_FIELD_NUMBER = 2;
  private HashPair hashPair_;
  /**
   * <code>.HashPair hashPair = 2;</code>
   */
  public boolean hasHashPair() {
    return hashPair_ != null;
  }
  /**
   * <code>.HashPair hashPair = 2;</code>
   */
  public HashPair getHashPair() {
    return hashPair_ == null ? HashPair.getDefaultInstance() : hashPair_;
  }
  /**
   * <code>.HashPair hashPair = 2;</code>
   */
  public HashPairOrBuilder getHashPairOrBuilder() {
    return getHashPair();
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (userId_ != 0) {
      output.writeInt32(1, userId_);
    }
    if (hashPair_ != null) {
      output.writeMessage(2, getHashPair());
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (userId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, userId_);
    }
    if (hashPair_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getHashPair());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof HashResponse)) {
      return super.equals(obj);
    }
    HashResponse other = (HashResponse) obj;

    if (getUserId()
        != other.getUserId()) return false;
    if (hasHashPair() != other.hasHashPair()) return false;
    if (hasHashPair()) {
      if (!getHashPair()
          .equals(other.getHashPair())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + USERID_FIELD_NUMBER;
    hash = (53 * hash) + getUserId();
    if (hasHashPair()) {
      hash = (37 * hash) + HASHPAIR_FIELD_NUMBER;
      hash = (53 * hash) + getHashPair().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static HashResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static HashResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static HashResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static HashResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static HashResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static HashResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static HashResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static HashResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static HashResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static HashResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static HashResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static HashResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(HashResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code HashResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:HashResponse)
      HashResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return PasswordServiceProto.internal_static_HashResponse_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return PasswordServiceProto.internal_static_HashResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              HashResponse.class, HashResponse.Builder.class);
    }

    // Construct using ronan_hanley.dist_sys.user_account_service.proto.HashResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      userId_ = 0;

      if (hashPairBuilder_ == null) {
        hashPair_ = null;
      } else {
        hashPair_ = null;
        hashPairBuilder_ = null;
      }
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return PasswordServiceProto.internal_static_HashResponse_descriptor;
    }

    @Override
    public HashResponse getDefaultInstanceForType() {
      return HashResponse.getDefaultInstance();
    }

    @Override
    public HashResponse build() {
      HashResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public HashResponse buildPartial() {
      HashResponse result = new HashResponse(this);
      result.userId_ = userId_;
      if (hashPairBuilder_ == null) {
        result.hashPair_ = hashPair_;
      } else {
        result.hashPair_ = hashPairBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof HashResponse) {
        return mergeFrom((HashResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(HashResponse other) {
      if (other == HashResponse.getDefaultInstance()) return this;
      if (other.getUserId() != 0) {
        setUserId(other.getUserId());
      }
      if (other.hasHashPair()) {
        mergeHashPair(other.getHashPair());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      HashResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (HashResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int userId_ ;
    /**
     * <code>int32 userId = 1;</code>
     */
    public int getUserId() {
      return userId_;
    }
    /**
     * <code>int32 userId = 1;</code>
     */
    public Builder setUserId(int value) {

      userId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 userId = 1;</code>
     */
    public Builder clearUserId() {

      userId_ = 0;
      onChanged();
      return this;
    }

    private HashPair hashPair_;
    private com.google.protobuf.SingleFieldBuilderV3<
        HashPair, HashPair.Builder, HashPairOrBuilder> hashPairBuilder_;
    /**
     * <code>.HashPair hashPair = 2;</code>
     */
    public boolean hasHashPair() {
      return hashPairBuilder_ != null || hashPair_ != null;
    }
    /**
     * <code>.HashPair hashPair = 2;</code>
     */
    public HashPair getHashPair() {
      if (hashPairBuilder_ == null) {
        return hashPair_ == null ? HashPair.getDefaultInstance() : hashPair_;
      } else {
        return hashPairBuilder_.getMessage();
      }
    }
    /**
     * <code>.HashPair hashPair = 2;</code>
     */
    public Builder setHashPair(HashPair value) {
      if (hashPairBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        hashPair_ = value;
        onChanged();
      } else {
        hashPairBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.HashPair hashPair = 2;</code>
     */
    public Builder setHashPair(
        HashPair.Builder builderForValue) {
      if (hashPairBuilder_ == null) {
        hashPair_ = builderForValue.build();
        onChanged();
      } else {
        hashPairBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.HashPair hashPair = 2;</code>
     */
    public Builder mergeHashPair(HashPair value) {
      if (hashPairBuilder_ == null) {
        if (hashPair_ != null) {
          hashPair_ =
            HashPair.newBuilder(hashPair_).mergeFrom(value).buildPartial();
        } else {
          hashPair_ = value;
        }
        onChanged();
      } else {
        hashPairBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.HashPair hashPair = 2;</code>
     */
    public Builder clearHashPair() {
      if (hashPairBuilder_ == null) {
        hashPair_ = null;
        onChanged();
      } else {
        hashPair_ = null;
        hashPairBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.HashPair hashPair = 2;</code>
     */
    public HashPair.Builder getHashPairBuilder() {

      onChanged();
      return getHashPairFieldBuilder().getBuilder();
    }
    /**
     * <code>.HashPair hashPair = 2;</code>
     */
    public HashPairOrBuilder getHashPairOrBuilder() {
      if (hashPairBuilder_ != null) {
        return hashPairBuilder_.getMessageOrBuilder();
      } else {
        return hashPair_ == null ?
            HashPair.getDefaultInstance() : hashPair_;
      }
    }
    /**
     * <code>.HashPair hashPair = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        HashPair, HashPair.Builder, HashPairOrBuilder>
        getHashPairFieldBuilder() {
      if (hashPairBuilder_ == null) {
        hashPairBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            HashPair, HashPair.Builder, HashPairOrBuilder>(
                getHashPair(),
                getParentForChildren(),
                isClean());
        hashPair_ = null;
      }
      return hashPairBuilder_;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:HashResponse)
  }

  // @@protoc_insertion_point(class_scope:HashResponse)
  private static final HashResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new HashResponse();
  }

  public static HashResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<HashResponse>
      PARSER = new com.google.protobuf.AbstractParser<HashResponse>() {
    @Override
    public HashResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new HashResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<HashResponse> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<HashResponse> getParserForType() {
    return PARSER;
  }

  @Override
  public HashResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

