// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: password-service.proto

package ronan_hanley.dist_sys.user_account_service.proto;

public interface HashResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:HashResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 userId = 1;</code>
   */
  int getUserId();

  /**
   * <code>.HashPair hashPair = 2;</code>
   */
  boolean hasHashPair();
  /**
   * <code>.HashPair hashPair = 2;</code>
   */
  HashPair getHashPair();
  /**
   * <code>.HashPair hashPair = 2;</code>
   */
  HashPairOrBuilder getHashPairOrBuilder();
}
