// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: password-service.proto

package ronan_hanley.dist_sys.user_account_service.proto;

public interface HashPairOrBuilder extends
    // @@protoc_insertion_point(interface_extends:HashPair)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes hash = 1;</code>
   */
  com.google.protobuf.ByteString getHash();

  /**
   * <code>bytes salt = 2;</code>
   */
  com.google.protobuf.ByteString getSalt();
}
