// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: password-service.proto

package ronan_hanley.dist_sys.user_account_service.proto;

public interface ValidateResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ValidateResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool valid = 1;</code>
   */
  boolean getValid();
}
