// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: password-service.proto

package ronan_hanley.dist_sys.user_account_service.proto;

/**
 * Protobuf type {@code ValidateRequest}
 */
public  final class ValidateRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ValidateRequest)
    ValidateRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ValidateRequest.newBuilder() to construct.
  private ValidateRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ValidateRequest() {
    password_ = "";
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new ValidateRequest();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ValidateRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            String s = input.readStringRequireUtf8();

            password_ = s;
            break;
          }
          case 18: {
            HashPair.Builder subBuilder = null;
            if (hashPair_ != null) {
              subBuilder = hashPair_.toBuilder();
            }
            hashPair_ = input.readMessage(HashPair.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(hashPair_);
              hashPair_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return PasswordServiceProto.internal_static_ValidateRequest_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return PasswordServiceProto.internal_static_ValidateRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ValidateRequest.class, ValidateRequest.Builder.class);
  }

  public static final int PASSWORD_FIELD_NUMBER = 1;
  private volatile Object password_;
  /**
   * <code>string password = 1;</code>
   */
  public String getPassword() {
    Object ref = password_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      password_ = s;
      return s;
    }
  }
  /**
   * <code>string password = 1;</code>
   */
  public com.google.protobuf.ByteString
      getPasswordBytes() {
    Object ref = password_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      password_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int HASHPAIR_FIELD_NUMBER = 2;
  private HashPair hashPair_;
  /**
   * <code>.HashPairRep hashPair = 2;</code>
   */
  public boolean hasHashPair() {
    return hashPair_ != null;
  }
  /**
   * <code>.HashPairRep hashPair = 2;</code>
   */
  public HashPair getHashPair() {
    return hashPair_ == null ? HashPair.getDefaultInstance() : hashPair_;
  }
  /**
   * <code>.HashPairRep hashPair = 2;</code>
   */
  public HashPairOrBuilder getHashPairOrBuilder() {
    return getHashPair();
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getPasswordBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, password_);
    }
    if (hashPair_ != null) {
      output.writeMessage(2, getHashPair());
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getPasswordBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, password_);
    }
    if (hashPair_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getHashPair());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ValidateRequest)) {
      return super.equals(obj);
    }
    ValidateRequest other = (ValidateRequest) obj;

    if (!getPassword()
        .equals(other.getPassword())) return false;
    if (hasHashPair() != other.hasHashPair()) return false;
    if (hasHashPair()) {
      if (!getHashPair()
          .equals(other.getHashPair())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + PASSWORD_FIELD_NUMBER;
    hash = (53 * hash) + getPassword().hashCode();
    if (hasHashPair()) {
      hash = (37 * hash) + HASHPAIR_FIELD_NUMBER;
      hash = (53 * hash) + getHashPair().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ValidateRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ValidateRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ValidateRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ValidateRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ValidateRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ValidateRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ValidateRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ValidateRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ValidateRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ValidateRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ValidateRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ValidateRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ValidateRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ValidateRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ValidateRequest)
      ValidateRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return PasswordServiceProto.internal_static_ValidateRequest_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return PasswordServiceProto.internal_static_ValidateRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ValidateRequest.class, ValidateRequest.Builder.class);
    }

    // Construct using ronan_hanley.dist_sys.user_account_service.proto.ValidateRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      password_ = "";

      if (hashPairBuilder_ == null) {
        hashPair_ = null;
      } else {
        hashPair_ = null;
        hashPairBuilder_ = null;
      }
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return PasswordServiceProto.internal_static_ValidateRequest_descriptor;
    }

    @Override
    public ValidateRequest getDefaultInstanceForType() {
      return ValidateRequest.getDefaultInstance();
    }

    @Override
    public ValidateRequest build() {
      ValidateRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public ValidateRequest buildPartial() {
      ValidateRequest result = new ValidateRequest(this);
      result.password_ = password_;
      if (hashPairBuilder_ == null) {
        result.hashPair_ = hashPair_;
      } else {
        result.hashPair_ = hashPairBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ValidateRequest) {
        return mergeFrom((ValidateRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ValidateRequest other) {
      if (other == ValidateRequest.getDefaultInstance()) return this;
      if (!other.getPassword().isEmpty()) {
        password_ = other.password_;
        onChanged();
      }
      if (other.hasHashPair()) {
        mergeHashPair(other.getHashPair());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ValidateRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ValidateRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private Object password_ = "";
    /**
     * <code>string password = 1;</code>
     */
    public String getPassword() {
      Object ref = password_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        password_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string password = 1;</code>
     */
    public com.google.protobuf.ByteString
        getPasswordBytes() {
      Object ref = password_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        password_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string password = 1;</code>
     */
    public Builder setPassword(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }

      password_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string password = 1;</code>
     */
    public Builder clearPassword() {

      password_ = getDefaultInstance().getPassword();
      onChanged();
      return this;
    }
    /**
     * <code>string password = 1;</code>
     */
    public Builder setPasswordBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

      password_ = value;
      onChanged();
      return this;
    }

    private HashPair hashPair_;
    private com.google.protobuf.SingleFieldBuilderV3<
        HashPair, HashPair.Builder, HashPairOrBuilder> hashPairBuilder_;
    /**
     * <code>.HashPairRep hashPair = 2;</code>
     */
    public boolean hasHashPair() {
      return hashPairBuilder_ != null || hashPair_ != null;
    }
    /**
     * <code>.HashPairRep hashPair = 2;</code>
     */
    public HashPair getHashPair() {
      if (hashPairBuilder_ == null) {
        return hashPair_ == null ? HashPair.getDefaultInstance() : hashPair_;
      } else {
        return hashPairBuilder_.getMessage();
      }
    }
    /**
     * <code>.HashPairRep hashPair = 2;</code>
     */
    public Builder setHashPair(HashPair value) {
      if (hashPairBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        hashPair_ = value;
        onChanged();
      } else {
        hashPairBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.HashPairRep hashPair = 2;</code>
     */
    public Builder setHashPair(
        HashPair.Builder builderForValue) {
      if (hashPairBuilder_ == null) {
        hashPair_ = builderForValue.build();
        onChanged();
      } else {
        hashPairBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.HashPairRep hashPair = 2;</code>
     */
    public Builder mergeHashPair(HashPair value) {
      if (hashPairBuilder_ == null) {
        if (hashPair_ != null) {
          hashPair_ =
            HashPair.newBuilder(hashPair_).mergeFrom(value).buildPartial();
        } else {
          hashPair_ = value;
        }
        onChanged();
      } else {
        hashPairBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.HashPairRep hashPair = 2;</code>
     */
    public Builder clearHashPair() {
      if (hashPairBuilder_ == null) {
        hashPair_ = null;
        onChanged();
      } else {
        hashPair_ = null;
        hashPairBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.HashPairRep hashPair = 2;</code>
     */
    public HashPair.Builder getHashPairBuilder() {

      onChanged();
      return getHashPairFieldBuilder().getBuilder();
    }
    /**
     * <code>.HashPairRep hashPair = 2;</code>
     */
    public HashPairOrBuilder getHashPairOrBuilder() {
      if (hashPairBuilder_ != null) {
        return hashPairBuilder_.getMessageOrBuilder();
      } else {
        return hashPair_ == null ?
            HashPair.getDefaultInstance() : hashPair_;
      }
    }
    /**
     * <code>.HashPairRep hashPair = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        HashPair, HashPair.Builder, HashPairOrBuilder>
        getHashPairFieldBuilder() {
      if (hashPairBuilder_ == null) {
        hashPairBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            HashPair, HashPair.Builder, HashPairOrBuilder>(
                getHashPair(),
                getParentForChildren(),
                isClean());
        hashPair_ = null;
      }
      return hashPairBuilder_;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ValidateRequest)
  }

  // @@protoc_insertion_point(class_scope:ValidateRequest)
  private static final ValidateRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ValidateRequest();
  }

  public static ValidateRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ValidateRequest>
      PARSER = new com.google.protobuf.AbstractParser<ValidateRequest>() {
    @Override
    public ValidateRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ValidateRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ValidateRequest> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<ValidateRequest> getParserForType() {
    return PARSER;
  }

  @Override
  public ValidateRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

